---
- name: About to Check the current user
  hosts: localhost
  connection: local
  gather_facts: no
  user: root
  tasks:
  - name: Checking user
    shell: whoami
    register: user
    
  - name: Debugging
    debug:
      var: user
