---
- name: Execute Postgres drop db Script
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  vars:
    db_new: class_of
    
  tasks:
  - name: Drop database
    postgresql_db:
      name: "{{ db_new }}_ntek"
      state: absent
    register: dbcreate
    
  - name: Debugging outputs
    debug:
      msg: The {{ db_new }}_ntek database has been successfully dropped
      
  - name: Connect to {{ db_new }}ntek database, drop user
    postgresql_user:
      name: "{{ db_new }}_ntek"
      password: ceec4eif7ya
      state: absent
    ignore_errors: true

  - name: Debugging outputs
    debug:
      msg: The user {{ db_new }}_ntek has been successfully dropped.
