- name: Hello World Sample
  hosts: "{{ hostname }}"
  connection: local
  gather_facts: true
  become_user: awx
  tasks:
  - name: Check location
    command: hostname
    register: hostname
  
  - name: Hello Message
    debug:
      msg: "Hello Ansible_Tower!"
