- name: Hello World Sample
  hosts: localhost
  connection: local
  gather_facts: true
  become_user: awx
  tasks:
  - name: Hello Message
    debug:
      msg: "Hello Ansible_Tower!"
    delegate_to: 192.168.0.102
