---
- name: Execute Linux Patch Script
  hosts: localhost
  connection: local
  gather_facts: yes
  user: root
  tasks:
  
  - name: Check location
    command: whoami
    register: user
    
  - name: Hello Message
    debug:
      var: user
      
  - name: installing updated packages
    yum:
      security: yes
      name: '*'
      state: absent
      exclude: kernel*
    register: patch_linux_updated

#  - name: set fact if COMPLETE
#    set_fact:
#      linux_patching_fact: "complete"
#      cacheable: yes
#    when: patch_linux_updated.rc == 0

#  - name: set fact if FAILED
#    set_fact:
#      linux_patching_fact: "failed"
#      cacheable: yes
#    when: patch_linux_updated.failed == true
