---
- name: Execute Linux Patch Script
  hosts: all
  gather_facts: yes
  become: yes
  become_method: sudo
  tasks:
  
  - name: installing updated packages
    yum:
      security: yes
      name: '*'
      state: latest
      exclude: kernel*
    register: patch_linux_updated

  - name: set fact if COMPLETE
    set_fact:
      linux_patching_fact: "complete"
      cacheable: yes
    when: patch_linux_updated.rc == 0

  - name: set fact if FAILED
    set_fact:
      linux_patching_fact: "failed"
      cacheable: yes
    when: patch_linux_updated.failed == true
    
  - name: Debug results
    debug:
      msg: The linux {{ patch_linux_updated }}.rc is successfully completed !!!
