---
- name: Execute Linux Patch Script
  hosts: "{{ hostname }}"
  connection: local
  gather_facts: yes
  become_method: su
  user: root
  tasks:
  
  - name: Check location
    command: whoami
    register: user
    
  - name: Add test file
    file:
      path: /test_file
      mode: 0755
      state: touch
    
  - name: Hello Message
    debug:
      var: user.stdout_lines
      
#  - name: installing updated packages
#    yum:
#      security: yes
#      name: '*'
#      state: absent
#      exclude: kernel*
#    register: patch_linux_updated

#  - name: set fact if COMPLETE
#    set_fact:
#      linux_patching_fact: "complete"
#      cacheable: yes
#    when: patch_linux_updated.rc == 0

#  - name: set fact if FAILED
#    set_fact:
#      linux_patching_fact: "failed"
#      cacheable: yes
#    when: patch_linux_updated.failed == true
