---
- name: Add Host to Dynamic Inventory
  hosts: localhost
  connection: local
  gather_facts: no
  become_user: root
  tasks: 
  - name: Adding hosts to dynamic inventory
    add_host:
      name: "{{ item }}"
      groups: dynamic
    with_items: "{{ hostname }}"
    changed_when: false
  tags:
    - always

- name: Running 'Test' test Playbook
  hosts: dynamic
  ignore_unreachable: false
  gather_facts: true
  gather_subset:
    - '!all'
    - min
    - hardware
  serial: "100%"

  roles:
#    - name: roles/postgres
#    - name: roles/installations
