- name: Create a new database in a tablespace
  postgresql_db:
    name: "{{ db_new }}_ntek"
    state: absent
  register: dbcreate
    
- name: Debugging outputs
  debug:
    msg: The "{{ db_new }}_ntek" database has been successfully dropped
