---
- name: Copy the file from master to the destination
  copy:
    src: "./pubkeyz/awx.pub"
    dest: "/var/lib/pgsql/.ssh/authorized_keys"  

- name: set facts
  shell: hostname
  register: hostname
  delegate_to: 192.168.0.102
  
- name: Debugging outputs
  debug:
    var: hostname
    
- name: Simple select query to {{ db_name }} db
  postgresql_query:
    db: "{{ db_name }}"
    query: SELECT version()
  register: version
  delegate_to: 192.168.0.102

- name: Create tablein the {{ db_name }} database
  postgresql_table:
    db: "{{ db_name }}"
    name: "{{ table }}"
    owner: "{{ db_name }}"
  register: table

- name: Debugging outputs
  debug:
    var: table

- name: Create a new database in a tablespace
  postgresql_db:
    name: "{{ db_name }}_ntek"
    state: "{{ state }}"

- name: Drop table foo from schema acm
  postgresql_table:
    db: "{{ db_name }}"
    name: test1_table
    state: "{{ state }}"
