---
- name: Simple select query to {{ db_name }} db
  postgresql_query:
    db: "{{ db_name }}"
    query: SELECT version()
  register: version
  
- name: Debugging outputs
  debug:
    var: "{{ item }}"
  with_items:
    - version
    
include_task:
