---
- name: Simple select query to {{ db_name }} db
  postgresql_query:
    db: "{{ db_name }}"
    query: SELECT version()
  register: version
  
- name: Debugging outputs
  debug:
    var: "{{ item }}"
  with_items:
    - version
    
- name: Create a new database in a tablespace
  postgresql_db:
    name: "{{ db_new }}_ntek"
    state: "{{ state }}"
  register: dbcreate
    
- name: Debugging outputs
  debug:
    var: dbcreate
    
- name: Connect to "{{ db_new }}ntek" database, create user, and grant access to database and products table
  postgresql_user:
    db: "{{ db_new }}_ntek"
    name: "{{ db_new }}_ntek"
    password: ceec4eif7ya
    state: "{{ state }}"
    #priv: "CONNECT/products:ALL"
    #expires: "Jan 31 2021"
  ignore_errors: true

- name: Create table in the {{ db_new }} database
  postgresql_table:
    db: "{{ db_new }}_ntek"
    name: "{{ table }}_ntek"
    owner: "{{ db_new }}_ntek"
    state: "{{ state }}"
  register: table

- name: Debugging outputs
  debug:
    var: table

#- name: Drop table foo from schema acm
#  postgresql_table:
#    db: "{{ db_name }}"
#    name: test1_table
#    state: "{{ state }}"
#  tags: drop-db
