---
- name: Simple select query to {{ db_name }} db
  postgresql_query:
    db: "{{ db_name }}"
    query: SELECT version()
  register: version
  
- name: Lookup database query to {{ db_name }} db
  postgresql_query:
    db: "{{ db_name }}"
    query: select * from summer2020;
  register: lookup
  
- name: Debugging outputs
  debug:
    var: "{{ item }}"
  with_items:
    - version
    - lookup.first_name

#- name: Create tablein the {{ db_name }} database
#  postgresql_table:
#    db: "{{ db_name }}"
#    name: "{{ table }}"
#    owner: "{{ db_name }}"
#  register: table

#- name: Debugging outputs
#  debug:
#    var: table

#- name: Create a new database in a tablespace
#  postgresql_db:
#    name: "{{ db_name }}_ntek"
#    state: "{{ state }}"

#- name: Drop table foo from schema acm
#  postgresql_table:
#    db: "{{ db_name }}"
#    name: test1_table
#    state: "{{ state }}"
