---
- name: Copy the file from master to the destination
  shell: pwd
  register: pwd

- name: set facts
  shell: whoami
  register: user
  
- name: Make a new folder
  file:
    path: /var/lib/awx/projects/AWX-FOLDER
    mode: 0755
    state: absent
  delegate_to: 192.168.0.102
  
- name: Debugging outputs
  debug:
    var: "{{ item }}"
  with_items:
    - pwd.stdout_lines
    - user.stdout_lines
    
- name: Simple select query to {{ db_name }} db
  postgresql_query:
    db: "{{ db_name }}"
    query: SELECT version()
  register: version
  delegate_to: 192.168.0.102

- name: Create tablein the {{ db_name }} database
  postgresql_table:
    db: "{{ db_name }}"
    name: "{{ table }}"
    owner: "{{ db_name }}"
  register: table

- name: Debugging outputs
  debug:
    var: table

- name: Create a new database in a tablespace
  postgresql_db:
    name: "{{ db_name }}_ntek"
    state: "{{ state }}"

- name: Drop table foo from schema acm
  postgresql_table:
    db: "{{ db_name }}"
    name: test1_table
    state: "{{ state }}"
