---
- name: Create table in the {{ db_new }}_ntek database
  postgresql_table:
    db: "{{ db_new }}_ntek"
    name: "{{ table }}_ntek"
    owner: "{{ db_new }}_ntek"
    state: present
  register: table

- name: Debugging outputs
  debug:: The {{ table }}_ntek table has been successfully created !!!!
