---  
- name: Connect to {{ db_new }}_ntek database, create user, and grant access to database and products table
  postgresql_user:
    db: "{{ db_new }}_ntek"
    name: "{{ db_new }}_ntek"
    password: ceec4eif7ya
    state: present
    priv: ALL
    expires: infinity
  ignore_errors: true

- name: Debugging outputs
  debug:
    msg: The {{ db_new }}_ntek user has been successfully created !!!
    
#- name: ALter Role query to {{ db_name }} Superuser
#  postgresql_query:
#    db: "{{ db_new }}_ntek"
#    query: ALTER USER "{{ db_new }}_ntek" WITH SUPERUSER;
#  register: alter
  
#- name: ALter Role query to {{ db_name }} Replicate
#  postgresql_query:
#    db: "{{ db_new }}_ntek"
#    query: ALTER USER "{{ db_new }}_ntek" WITH REPLICATION;
#  register: alter
  
#- name: Debugging outputs
#  debug:
#    var: alter
