---  
- name: Connect to {{ db_new }}_ntek database, create user, and grant access to database and products table
  postgresql_user:
    db: "{{ db_new }}_ntek"
    name: "{{ db_new }}_ntek"
    password: ceec4eif7ya
    state: present
    priv: ALL
    expires: infinity
  ignore_errors: true

- name: Debugging outputs
  debug:
    msg: The {{ db_new }}_ntek user has been successfully created !!!

- name: GRANT ALL PRIVILEGES ON DATABASE {{ db_new }}_ntek TO {{ db_new }}_ntek
  postgresql_privs:
    db: postgres
    privs: ALL
    type: database
    role: "{{ db_new }}_ntek"
    
- name: Simple select query to {{ db_name }} db
  postgresql_query:
    db: "{{ db_new }}_ntek"
    query: ALTER USER "{{ db_new }}_ntek" WITH SUPERUSER;
  register: alter
  
- name: Debugging outputs
  debug:
    var: alter
