---  
- name: Connect to {{ db_new }}_ntek database, create user, and grant access to database and products table
  postgresql_user:
    db: "{{ db_new }}_ntek"
    name: "{{ db_new }}_ntek"
    password: ceec4eif7ya
    state: present
    #priv: "CONNECT/products:ALL"
    #expires: "Jan 31 2021"
  ignore_errors: true

- name: Debugging outputs
  debug:
    msg: The {{ db_new }}_ntek user has been successfully created !!!

#- name: Grant privs to "{{ db_new }}_ntek" role
#  postgresql_privs:
#    db: "{{ db_new }}_ntek"
#    privs: SELECT,INSERT,UPDATE
#    objs: linux,authors
#    roles: "{{ db_new }}_ntek"
#    grant_option: yes
#  register: grant
  
- name: Debugging outputs
  debug:
    var: grant
